version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE}
      - WATCHTOWER_CLEANUP=true
      # - WATCHTOWER_RUN_ONCE=true
    restart: always
